#Application Configuration
server:
  port: 8003

spring:
  profiles:
    active: dev

  #Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/one-master
    driverClassName: org.postgresql.Driver
    username: ms_login
    password: Access2024
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false